### ISSUE TITLE
Getting user data

### ISSUE THREAD

**Issue by fnakstad** [gologo13/passport-rakuten#1]
Hi, I'm working on a project where we would like to use Rakuten as an OAuth strategy for our users. I tried using this module, and got it working quite quickly. However, it seems that Rakuten doesn't return any user data at all (not even a user ID!). So ,my question is... If you can't differentiate between users performing a Rakuten login or store a reference to them in your DB, what exactly is the point of it? The only allowed scope parameter seems to be `rakuten_favoritebookmark_read`, which just returns bookmark info. Am I missing something here?

**Comment by gologo13** [comment]
Thank you for trying my module. 
I think you are right. I'm afraid you can't differentiate between users from the response of the Rakuten OAuth API.
Also, there is no userinfo API. The list of the Rakuten API is available here, https://webservice.rakuten.co.jp/document/.

**Comment by fnakstad** [comment]
Ah, that's too bad. Thanks for the quick response and making this module available :)
